name: torchgpu
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py312h885b0b7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=py312haa95532_0
  - krb5=1.21.3=hdf4eb48_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py312h02ab6af_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.11=h716150d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pywin32=311=py312h885b0b7_0
  - pyzmq=27.1.0=py312h7149c55_0
  - setuptools=80.9.0=py312haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py312h827c3e9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - pip:
    - anndata==0.12.4
    - anyio==4.11.0
    - array-api-compat==1.12.0
    - bio==1.8.1
    - biopython==1.86
    - biothings-client==0.4.1
    - certifi==2025.10.5
    - charset-normalizer==3.4.4
    - contourpy==1.3.3
    - cramjam==2.11.0
    - crc32c==2.8
    - cycler==0.12.1
    - donfig==0.8.1.post1
    - et-xmlfile==2.0.0
    - fastparquet==2024.11.0
    - filelock==3.13.1
    - fonttools==4.60.1
    - fsspec==2024.6.1
    - gprofiler-official==1.0.0
    - h11==0.16.0
    - h5py==3.15.1
    - httpcore==1.0.9
    - httpx==0.28.1
    - idna==3.11
    - jinja2==3.1.4
    - joblib==1.5.2
    - kiwisolver==1.4.9
    - legacy-api-wrap==1.4.1
    - llvmlite==0.45.1
    - markupsafe==2.1.5
    - matplotlib==3.10.7
    - mpmath==1.3.0
    - mygene==3.2.2
    - natsort==8.4.0
    - networkx==3.3
    - numba==0.62.1
    - numcodecs==0.16.3
    - numpy==2.1.2
    - openpyxl==3.1.5
    - pandas==2.3.3
    - patsy==1.0.2
    - pillow==11.0.0
    - pooch==1.8.2
    - pyarrow==22.0.0
    - pyfaidx==0.9.0.3
    - pynndescent==0.5.13
    - pyparsing==3.2.5
    - pytz==2025.2
    - pyyaml==6.0.3
    - requests==2.32.5
    - scanpy==1.11.5
    - scikit-learn==1.7.2
    - scipy==1.16.2
    - seaborn==0.13.2
    - session-info2==0.2.3
    - sniffio==1.3.1
    - statsmodels==0.14.5
    - sympy==1.13.3
    - threadpoolctl==3.6.0
    - torch==2.8.0+cu126
    - torchvision==0.23.0+cu126
    - tqdm==4.67.1
    - typing-extensions==4.12.2
    - tzdata==2025.2
    - umap-learn==0.5.9.post2
    - urllib3==2.5.0
    - zarr==3.1.3
prefix: C:\Users\navid\anaconda3\envs\torchgpu
